# Config
polling_time: 15 # Timeout in minutes
default_folder: "INBOX"

accounts:
  ex1_mon:
    username: "monitor-only@example.com"
    password: "VeryStrongPassword"
    imap_host: "imap.example.com"
    imap_port: 993
    imap_ssl: true
    
  ex2_mon_send:
    username: "monitor-and-send@example.com"
    password: "VeryStrongPassword"
    imap_host: "imap.example.com"
    imap_port: 993
    imap_ssl: true
    smtp_host: "smtp.example.com"
    smtp_port: 587
    smtp_tls: true
    
alerts:
 - monitor: ex1_mon
   sender: ex2_mon_send
   alert:
     - "alert-me@example.com"
     - "alert-me-too@example.com"
   subject: "New mail on monitor-only@example.com"
   
 - monitor: ex2_mon_send
   sender: ex2_mon_send
   alert:
     - "alert-me@example.com"
     - "alert-me-too@example.com"
   subject: "New mail on monitor-and-send@example.com"